esphome:
  name: front-door
  friendly_name: Front Door

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret api_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Front-Door-AP"
    password: !secret fallback_ap_password

captive_portal:

web_server:
  port: 80
  local: true
  ota: false
  auth:
    username: !secret web_front_door_username
    password: !secret web_front_door_password

sensor:
  - platform: wifi_signal
    name: "WiFi Strength"
    update_interval: 60s
  - platform: uptime
    name:  "Uptime"
binary_sensor:
  - platform: status
    name: "Connectivity"
  - platform: gpio
    pin:
      number: GPIO4
      mode: INPUT
      inverted: true
    name: "Door State"
    device_class: opening
    id: sensor_bottom
    filters:
      - invert:
      - delayed_on_off: 1.5s
output:
  - platform: gpio
    pin: GPIO13
    id: open_switch
    inverted: false
  - platform: gpio
    pin: GPIO14
    id: close_switch
    inverted: false
  - platform: gpio
    pin: GPIO12
    id: stop_switch
    inverted: false
cover:
  - platform: template
    name: "Front Door"
    lambda: |-
      if (!id(sensor_bottom).state) {
        return COVER_CLOSED;
      } else {
        return COVER_OPEN;
      }
    optimistic: true
    assumed_state: true
    open_action:
      - output.turn_off: stop_switch
      - output.turn_off: close_switch
      - output.turn_on: open_switch
      - delay: 0.1s
      - output.turn_off: open_switch
    close_action:
      - output.turn_off: stop_switch
      - output.turn_off: open_switch
      - output.turn_on: close_switch
      - delay: 0.1s
      - output.turn_off: close_switch
    stop_action:
      - output.turn_off: open_switch
      - output.turn_off: close_switch
      - output.turn_on: stop_switch
      - delay: 0.1s
      - output.turn_off: stop_switch
switch:
  - platform: restart
    name: "Restart"