esphome:
  name: front-sensor

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret api_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Front-Sensor-AP"
    password: !secret fallback_ap_password

captive_portal:

i2c:
  sda: D3
  scl: D4
  scan: true
  id: bus_a

sensor:
  - platform: wifi_signal
    name: "Front Sensor WiFi Strength"
    update_interval: 60s
  - platform: uptime
    name:  "Uptime"
  - platform: bh1750
    name: "Front Illuminance"
    address: 0x23
    update_interval: 60s